<?php

use App\Locale;
use App\Talk;
use App\TalkSubject;
use App\User;
use Illuminate\Database\Seeder;

class TalksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('talks')->delete();
        DB::table('talk_subjects')->delete();

        $ht_talks = [
            ['number' => 1, 'subject' => 'Eske w byen konnen Bondye?'],
            ['number' => 2, 'subject' => 'Eske n ap chape nan denye jou yo?'],
            ['number' => 3, 'subject' => 'Annou sevi Jewova nan oganizasyon l lan ki ini'],
            ['number' => 4, 'subject' => 'Monn ki antoure nou an bay prev Bondye egziste'],
            ['number' => 5, 'subject' => 'Yonvi fanmi ki bay ke kontan'],
            ['number' => 6, 'subject' => 'Ki sa delij nan epok Noye a vle di pou nou?'],
            ['number' => 7, 'subject' => 'Mizerikod se youn nan kalite prensipal vre kretyen yo genyen'],
            ['number' => 8, 'subject' => 'Ann pa viv pou tet nou, men pito ann viv pou n fe volonte Bondye'],
            ['number' => 9, 'subject' => 'Pinga nou janm vin moun ki tande di'],
            ['number' => 10, 'subject' => 'Annou toujou aji yon fason ki onet'],
            ['number' => 11, 'subject' => 'Menm jan ak Kris, pinga nou “fe pati monn nan”'],
            ['number' => 12, 'subject' => 'Le n respekte otorite se yon pwoteksyon pou nou'],
            ['number' => 13, 'subject' => 'Ki sa Bondye di sou seks ak maryaj?'],
            ['number' => 14, 'subject' => 'Yon pep ki pwop ap onore Jewova'],
            ['number' => 15, 'subject' => 'Antanke kretyen, nou gen sousi pou lot moun'],
            ['number' => 16, 'subject' => 'Annou kontinye cheche gen pi bon relasyon ak Bondye'],
            ['number' => 17, 'subject' => 'Annou sevi ak tout sa n genyen pou n bay Bondye glwa'],
            ['number' => 18, 'subject' => 'Eske nou fe Jewova tounen fotres nou toutbonvre?'],
            ['number' => 19, 'subject' => 'Ki jan w ka rive konnen sa demen sere pou ou?'],
            ['number' => 20, 'subject' => 'Eske le a rive pou Bondye dirije monn nan?'],
            ['number' => 21, 'subject' => 'Ki janw ka montre w diy pou Wayom Bondye a?'],
            ['number' => 22, 'subject' => 'Eske w satisfe ak dispozisyon Jewova pran yo?'],
            ['number' => 23, 'subject' => 'Rezon ki fe nou egziste'],
            ['number' => 24, 'subject' => 'Byenfe n ap jwenn si nou kite Bondye dirije nou'],
            ['number' => 25, 'subject' => 'Annou reziste kont lespri monn nan'],
            ['number' => 26, 'subject' => 'Eske w gen vale nan je Bondye?'],
            ['number' => 27, 'subject' => 'Fason pou n byen komanse maryaj nou'],
            ['number' => 28, 'subject' => 'Demontre respe ak lanmou pou moun ou marye ave l la'],
            ['number' => 29, 'subject' => 'Responsablite paran yo genyen ak rekonpans yo jwenn'],
            ['number' => 30, 'subject' => 'Nan fanmi yo, li enpotan pou n kominike youn ak lot e avek Bondye'],
            ['number' => 31, 'subject' => 'Ki jan moun ki grangou ka gen ke kontan?'],
            ['number' => 32, 'subject' => 'Fason nou ka fe fas ak tetchaje ki gen nan lavi a'],
            ['number' => 33, 'subject' => 'Ki sa k fe moun gen tandans fe rebelyon?'],
            ['number' => 34, 'subject' => 'Eske w resevwa “mak” k ap pemet ou sove a?'],
            ['number' => 35, 'subject' => 'Eske l posib pou w viv pou toutan? Eske w pral viv pou toutan?'],
            ['number' => 36, 'subject' => 'Eske se vi sa a selman ki genyen?'],
            ['number' => 37, 'subject' => 'Depi kounye a, annou defann dwa Bondye genyen pou l dirije'],
            ['number' => 38, 'subject' => 'Annou aji avek sajes toutpandan lafen an ap pwoche'],
            ['number' => 39, 'subject' => 'Ann met konfyans nou nan viktwa Bondye pral ranpote a'],
            ['number' => 40, 'subject' => 'Ki sa demen sere pou nou?'],
            ['number' => 41, 'subject' => '“Rete trankil, epi gade ki jan Jewova ap sove nou”'],
            ['number' => 42, 'subject' => 'Ki enfliyans Wayom Bondye a gen sou vi w?'],
            ['number' => 43, 'subject' => 'Eske nou fe sa Bondye mande nou?'],
            ['number' => 44, 'subject' => 'Annou kontinye cheche Wayom Bondye a'],
            ['number' => 45, 'subject' => 'Annou mache sou wout lavi a'],
            ['number' => 46, 'subject' => 'Annou kenbe konfyans nou genyen an fem jiska lafen'],
            ['number' => 47, 'subject' => '“Se pou nou gen lafwa nan bon nouvel la”'],
            ['number' => 48, 'subject' => 'Antanke kretyen, annou lite pou n ret fidel'],
            ['number' => 49, 'subject' => 'Eske nou gen pou nviv sou yon te ki pwop?'],
            ['number' => 50, 'subject' => 'Ki jan pou nou pran bon desizyon?'],
            ['number' => 51, 'subject' => 'Eske laverite chanje lavi w?'],
            ['number' => 52, 'subject' => 'Kiyes ki Bondye w?'],
            ['number' => 53, 'subject' => 'Eske panse w ann amoni ak panse Bondye?'],
            ['number' => 54, 'subject' => 'Fotifye lafwa w nan Sila a ki kreye lom nan'],
            ['number' => 55, 'subject' => 'Ki repitasyon nou genyen devan Bondye?'],
            ['number' => 56, 'subject' => 'Annou antre nan monn nouvo a anba direksyon Kris'],
            ['number' => 57, 'subject' => 'Annou andire anba pesekisyon'],
            ['number' => 58, 'subject' => 'Ki jan nou ta dwe sevi Bondye?'],
            ['number' => 59, 'subject' => 'Sa nou simen se li n ap rekolte'],
            ['number' => 60, 'subject' => 'Poukisa n ap viv?'],
            ['number' => 61, 'subject' => 'Pwomes kiyes ou fe konfyans?'],
            ['number' => 62, 'subject' => 'Gen yon sel remed ki egziste pou limanite ki malad'],
            ['number' => 63, 'subject' => 'Eske w se yon moun ki renmen evanjelize?'],
            ['number' => 64, 'subject' => 'Eske w se zanmi plezi oswa zanmi Bondye?'],
            ['number' => 65, 'subject' => 'Nou jwenn one ak ke kontan nan sevis Bondye'],
            ['number' => 66, 'subject' => 'Annou travay kom esklav pou Met rekot la'],
            ['number' => 67, 'subject' => 'Annou pran tan pou n medite sou bagay ki gen rapo ak Bondye'],
            ['number' => 68, 'subject' => 'Eske w kenbe rankin oubyen eske w padone?'],
            ['number' => 69, 'subject' => 'Annou kontinye montre nou dispoze fe sakrifis'],
            ['number' => 70, 'subject' => 'Mete konfyans nou nan Jewova'],
            ['number' => 71, 'subject' => 'Fason pou nou rete je kle nan sevis Bondye'],
            ['number' => 72, 'subject' => 'Lanmou pemet moun idantifye vre kongregasyon kretyen an'],
            ['number' => 73, 'subject' => 'Annou cheche gen yon ke ki gen sajes'],
            ['number' => 74, 'subject' => 'Je Jewova ap gade nou'],
            ['number' => 75, 'subject' => 'Eske w rekonet souvrente Jewova nan lavi w?'],
            ['number' => 76, 'subject' => 'Eske prensip ki nan Bib la ka ede nou fe fas ak pwoblem ki gen jodi a?'],
            ['number' => 77, 'subject' => 'Pran abitid akeyi moun'],
            ['number' => 78, 'subject' => 'Annou sevi Jewova ak ke kontan'],
            ['number' => 79, 'subject' => 'Eske w ap chwazi fe zanmi ak Bondye oubyen ak monn nan?'],
            ['number' => 80, 'subject' => 'Eske se sou lasyans nou met espwa nou oubyen sou Labib?'],
            ['number' => 81, 'subject' => 'Kiyes ki kalifye pou vin sevite Bondye?'],
            ['number' => 82, 'subject' => 'Eske Jewova ak Kris fe pati yon trinite?'],
            ['number' => 83, 'subject' => 'Le jijman relijyon yo rive'],
            ['number' => 84, 'subject' => 'Eske w pral sibi menm so ak monn nan?'],
            ['number' => 85, 'subject' => 'Genyonbonnouvelnanyonmonnvyolan'],
            ['number' => 86, 'subject' => 'Priye Bondye tande yo'],
            ['number' => 87, 'subject' => 'Ki kalite relasyon ou gen ak Bondye?'],
            ['number' => 88, 'subject' => 'Poukisa nou dwe viv ann ako ak prensip ki nan Bib la?'],
            ['number' => 89, 'subject' => 'Vini, ou menm ki swaf verite!'],
            ['number' => 90, 'subject' => 'Lite pou w gen lavi toutbon an'],
            ['number' => 91, 'subject' => 'Prezans Mesi a ak rey li a'],
            ['number' => 92, 'subject' => 'Wol relijyon jwe nan zafe monn nan'],
            ['number' => 93, 'subject' => 'Eske se Bondye ki responsab katastwof natirel yo?'],
            ['number' => 94, 'subject' => 'Vre relijyon an satisfe bezwen lezom'],
            ['number' => 95, 'subject' => 'Sa Labib di sou pratik ki gen rapo ak movezespri yo'],
            ['number' => 96, 'subject' => 'Fo relijyon pral detwi tale konsa'],
            ['number' => 97, 'subject' => 'Annou rete san repwoch nan mitan yon jenerasyon ki kwochi'],
            ['number' => 98, 'subject' => 'Annou rete pwop parapo ak salte ki nan gen monn nan'],
            ['number' => 99, 'subject' => 'Rezon ki fe w ka fe Labib konfyans'],
            ['number' => 100, 'subject' => 'AnnouchechevinyonvrezanmipouBondyeepoupwochennou'],
            ['number' => 101, 'subject' => 'Jewova se Gran Kreyate a'],
            ['number' => 102, 'subject' => 'Annou fikse atansyon nou sou pawol ki ekri nan pwofesi yo'],
            ['number' => 103, 'subject' => 'Nou kapab jwenn ke kontan nan sevis Bondye a'],
            ['number' => 104, 'subject' => 'Paran, eske w ap bati ak materyo ki kapab reziste anba dife?'],
            ['number' => 105, 'subject' => 'Nou jwenn konsolasyon nan tout tribilasyon nou yo'],
            ['number' => 106, 'subject' => 'Bondye pral pini moun k ap detwi te a'],
            ['number' => 107, 'subject' => 'Se pou konsyans nou rete kle nan monn sa a k ap benyen nan peche'],
            ['number' => 108, 'subject' => 'Nou pa bezwen pe lavni'],
            ['number' => 109, 'subject' => 'Wayom Bondye a toupre'],
            ['number' => 110, 'subject' => 'Pou yon fanmi viv byen yo dwe met Bondye an premye'],
            ['number' => 111, 'subject' => 'Ki benediksyon gerizon nasyon yo ap jwenn nan pote?'],
            ['number' => 112, 'subject' => 'Fason nou ka demontre lanmou nan yon monn ki pa respekte lalwa'],
            ['number' => 113, 'subject' => 'Koman jen yo ka fe fas ak kriz ki gen nan monn nan jodi a?'],
            ['number' => 114, 'subject' => 'Annou apresye mevey ki gen nan kreyasyon Bondye a'],
            ['number' => 115, 'subject' => 'Ki jan nou ka pwoteje tet nou kont pyej Satan yo?'],
            ['number' => 116, 'subject' => 'Annou aji avek sajes le n ap chwazi ki moun n ap frekante'],
            ['number' => 117, 'subject' => 'Fason pou nou venk mal la avek byen'],
            ['number' => 118, 'subject' => 'Annou konsidere jen yo menm jan Jewova konsidere yo'],
            ['number' => 119, 'subject' => 'Ki benediksyon kretyen yo jwenn le yo ret separe ak monn nan?'],
            ['number' => 120, 'subject' => 'Rezon ki fe nou dwe soumet devan Bondye antanke Chef depi kounye a'],
            ['number' => 121, 'subject' => 'Fre yo nan lemonnantye delivre anba kalamite'],
            ['number' => 122, 'subject' => 'Ki sa k pral mete lape nan lemonnantye?'],
            ['number' => 123, 'subject' => 'Rezon ki fe kretyen yo dwe diferan'],
            ['number' => 124, 'subject' => 'Rezon ki fe nou gen konfyans se Bondye ki fe ekri Bib la'],
            ['number' => 125, 'subject' => 'Rezon ki fe limanite bezwen yon ranson'],
            ['number' => 126, 'subject' => 'Ki moun k ap sove?'],
            ['number' => 127, 'subject' => 'Sa k rive le nou mouri?'],
            ['number' => 128, 'subject' => 'Eske se vre lanfe se yon kote yo toumante moun nan dife?'],
            ['number' => 129, 'subject' => 'Eske trinite se yon anseyman ki nan Labib?'],
            ['number' => 130, 'subject' => 'Te a ap rete la pou toutan'],
            ['number' => 131, 'subject' => 'Eske Dyab la egziste toutbonvre?'],
            ['number' => 132, 'subject' => 'Grasa rezireksyon, n ap pot laviktwa sou lanmo'],
            ['number' => 133, 'subject' => 'Eske sa nou kwe sou orijin lom gen enpotans?'],
            ['number' => 134, 'subject' => 'Eske kretyen yo dwe obseve saba?'],
            ['number' => 135, 'subject' => 'Lavi ak san se bagay ki sakre'],
            ['number' => 136, 'subject' => 'Eske Bondye dako pou n sevi ak imaj nan adorasyon n ap ba l?'],
            ['number' => 137, 'subject' => 'Eske mirak Bib la rapote yo te fet vre?'],
            ['number' => 138, 'subject' => 'Annou viv avek bonsans nan yon monn deprave'],
            ['number' => 139, 'subject' => 'Cheche gen sajes Bondye nan monn sa a ki met konfyans li nan lasyans'],
            ['number' => 140, 'subject' => 'Jezi Kris se nouvo Chef te a'],
            ['number' => 141, 'subject' => 'Ki le limanite ap sispann jemi?'],
            ['number' => 142, 'subject' => 'Rezon ki fe nou dwe cheche pwoteksyon Jewova'],
            ['number' => 143, 'subject' => 'Annou mete konfyans nou nan Bondye tout konsolasyon an'],
            ['number' => 144, 'subject' => 'Yon kongregasyon ki fidel ki soumet anba otorite Kris'],
            ['number' => 145, 'subject' => 'Kiyes ki tankou Jewova, Bondye nou an?'],
            ['number' => 146, 'subject' => 'Annou sevi ak fomasyon nou resevwa yo pou nou louwe Jewova'],
            ['number' => 147, 'subject' => 'Ann met konfyans nou nan pouvwa Jewova genyen pou l sove nou'],
            ['number' => 148, 'subject' => 'Eske w konsidere lavi menm jan ak Bondye?'],
            ['number' => 149, 'subject' => 'Eske w ap mache ak Bondye?'],
            ['number' => 150, 'subject' => 'Eske Bondye vreman reyel pou ou?'],
            ['number' => 151, 'subject' => 'Jewova se “yon kote ki wo pou pwoteje” pep li'],
            ['number' => 152, 'subject' => 'Vre Amagedon an: poukisa l ap fet e ki le?'],
            ['number' => 153, 'subject' => 'Annou toujou kenbe ‘jou ki bay lakrentif la’ nan lespri nou!'],
            ['number' => 154, 'subject' => 'Le yo peze gouvenman lezom yo nan balans, ki sa yo jwenn?'],
            ['number' => 155, 'subject' => 'Eske le pou yo jije Babilon nan rive?'],
            ['number' => 156, 'subject' => 'Eske Jou jijman an se yon jou ki bay laperez oubyen ki bay espwa?'],
            ['number' => 157, 'subject' => 'FasonvrekretyenyofeanseymanBondyeavinpibel'],
            ['number' => 158, 'subject' => 'Mete kouraj sou nou, epi fe Jewova konfyans'],
            ['number' => 159, 'subject' => 'Fason pou nou jwenn sekirite nan yon monn ki danjere'],
            ['number' => 160, 'subject' => 'Ann pwoteje idantite nou antanke kretyen!'],
            ['number' => 161, 'subject' => 'Poukisa Jezi te soufri e li te mouri?'],
            ['number' => 162, 'subject' => 'Nou delivre anba yon monn fenwa'],
            ['number' => 163, 'subject' => 'Poukisa nou dwe gen krent pou vre Dye a?'],
            ['number' => 164, 'subject' => 'Eske se Bondye ki Souvren an toujou?'],
            ['number' => 165, 'subject' => 'Prensip kiyes nou bay plis vale?'],
            ['number' => 166, 'subject' => 'Annou fe fas ak lavni avek lafwa ak kouraj'],
            ['number' => 167, 'subject' => 'Annou aji avek sajes nan yon monn ki ensanse'],
            ['number' => 168, 'subject' => 'Ou kapab santi w an sekirite nan monn sa a ki chaje ak pwoblem'],
            ['number' => 169, 'subject' => 'Poukisa nou dwe kite Bib la gide nou?'],
            ['number' => 170, 'subject' => 'Kiyes ki kalifye pou dirije limanite?'],
            ['number' => 171, 'subject' => 'Ou ka viv anpe depi kounye a e pou toutan!'],
            ['number' => 172, 'subject' => 'Ki jan Bondye we w?'],
            ['number' => 173, 'subject' => 'Selon Bondye, eske gen yon vre relijyon?'],
            ['number' => 174, 'subject' => 'Ki moun k ap kapab antre nan monn nouvo Bondye a?'],
            ['number' => 175, 'subject' => 'Ki sa k montre Bib la se Pawol Bondye toutbonvre?'],
            ['number' => 176, 'subject' => 'Ki le n ap gen lape ak sekirite toutbon an?'],
            ['number' => 177, 'subject' => 'Ki kote nou ka jwenn ed nan moman detres?'],
            ['number' => 178, 'subject' => 'Annou mache nan chemen entegrite a'],
            ['number' => 179, 'subject' => 'Ann rejte rev monn sa a e ann kontinye cheche reyalite Wayom nan'],
            ['number' => 180, 'subject' => 'Rezon ki fe esperans rezireksyon an dwe reyel pou nou'],
            ['number' => 181, 'subject' => 'Eske lafen an pa pi pre pase sa n panse?'],
            ['number' => 182, 'subject' => 'Sa Wayom Bondye a ap fe pou nou kounye a'],
            ['number' => 183, 'subject' => 'Pa ret ap gade bagay ki pa vo anyen!'],
            ['number' => 184, 'subject' => 'Eske lanmo mete fen nan tout bagay?'],
            ['number' => 185, 'subject' => 'Ki enfliyans laverite gen sou lavi w?'],
            ['number' => 186, 'subject' => 'Annou Ini Ak Pèp Bondye A Ki Gen Kè Kontan'],
            ['number' => 187, 'subject' => 'Annou Ini Ak Pèp Bondye A Ki Gen Kè Kontan'],
            ['number' => 188, 'subject' => 'Èske W Mete Konfyans Ou Nan Jewova?'],
        ];

        $es_talks = [
            ['number' => 1, 'subject' => '¿Conoce usted bien a Dios?'],
            ['number' => 2, 'subject' => '¿Será usted sobreviviente de los últimos días?'],
            ['number' => 3, 'subject' => 'Sirvamos con la organización unificada de Jehová'],
            ['number' => 4, 'subject' => 'El mundo que nos rodea prueba que Dios existe'],
            ['number' => 5, 'subject' => 'Un afectuoso ambiente familiar'],
            ['number' => 6, 'subject' => 'El Diluvio del día de Noé tiene significado para nosotros'],
            ['number' => 7, 'subject' => 'La misericordia, cualidad dominante de los cristianos verdaderos'],
            ['number' => 8, 'subject' => 'No viva para su yo, sino para hacer la voluntad de Dios'],
            ['number' => 9, 'subject' => 'Nunca permitamos que se nos embote el oído'],
            ['number' => 10, 'subject' => 'Conduciéndonos honradamente en todo tiempo'],
            ['number' => 11, 'subject' => '‘No ser parte del mundo’... a semejanza de Cristo'],
            ['number' => 12, 'subject' => 'El respeto a la autoridad nos protege'],
            ['number' => 13, 'subject' => 'Viendo el sexo y el matrimonio como los ve Dios'],
            ['number' => 14, 'subject' => 'Un pueblo limpio honra a Jehová'],
            ['number' => 15, 'subject' => 'Como cristianos, nos interesamos por los demás'],
            ['number' => 16, 'subject' => 'Siga estrechando su relación con Dios'],
            ['number' => 17, 'subject' => 'Que todo cuanto tengamos glorifique a Dios'],
            ['number' => 18, 'subject' => '¿Realmente hace usted de Jehová su plaza fuerte?'],
            ['number' => 19, 'subject' => 'Su futuro... ¿cómo puede saberse?'],
            ['number' => 20, 'subject' => '¿Es tiempo de que Dios gobierne el mundo?'],
            ['number' => 21, 'subject' => '¿Cómo puede usted colaborar con el Reino de Dios?'],
            ['number' => 22, 'subject' => '¿Está usted contento con las provisiones de Jehová?'],
            ['number' => 23, 'subject' => 'La vida sí tiene propósito'],
            ['number' => 24, 'subject' => 'Lo que puede hacer por nosotros la gobernación de Dios'],
            ['number' => 25, 'subject' => 'Resistamos el espíritu del mundo'],
            ['number' => 26, 'subject' => '¿Lo considera Dios a usted personalmente importante?'],
            ['number' => 27, 'subject' => 'Cómo iniciar bien el matrimonio'],
            ['number' => 28, 'subject' => 'Muestre respeto y amor en su matrimonio'],
            ['number' => 29, 'subject' => 'Responsabilidades y galardones de los padres'],
            ['number' => 30, 'subject' => 'La comunicación en la familia y con Dios'],
            ['number' => 31, 'subject' => '¿Cómo se puede ser feliz a pesar de tener hambre?'],
            ['number' => 32, 'subject' => 'Cómo enfrentarse a las inquietudes de la vida'],
            ['number' => 33, 'subject' => '¿Qué hay tras el espíritu de rebelión?'],
            ['number' => 34, 'subject' => '¿Está usted “marcado” para sobrevivir?'],
            ['number' => 35, 'subject' => '¿Puede usted vivir para siempre? ¿Lo logrará?'],
            ['number' => 36, 'subject' => '¿Es esta vida todo cuanto hay?'],
            ['number' => 37, 'subject' => 'Decida ahora a favor de la gobernación divina'],
            ['number' => 38, 'subject' => 'Obren prudentemente a medida que se acerca el fin'],
            ['number' => 39, 'subject' => '¡Seguros de la victoria divina!'],
            ['number' => 40, 'subject' => 'Lo que encierra el futuro cercano'],
            ['number' => 41, 'subject' => '“Esténse quietos y vean la salvación de Jehová”'],
            ['number' => 42, 'subject' => 'Cómo le afecta a usted el Reino de Dios'],
            ['number' => 43, 'subject' => '¿Cumple usted con los requisitos de Dios?'],
            ['number' => 44, 'subject' => 'Siga buscando el Reino de Dios'],
            ['number' => 45, 'subject' => 'Siga el camino a la vida'],
            ['number' => 46, 'subject' => 'Mantenga firme su confianza hasta el fin'],
            ['number' => 47, 'subject' => '‘Tenga fe en las buenas nuevas’'],
            ['number' => 48, 'subject' => 'La prueba de mantener lealtad cristiana'],
            ['number' => 49, 'subject' => 'Una Tierra limpia: ¿vivirá usted para verla?'],
            ['number' => 50, 'subject' => '¿Cómo tomará usted sus decisiones?'],
            ['number' => 51, 'subject' => '¿Está transformando la verdad su vida?'],
            ['number' => 52, 'subject' => '¿Quién es su Dios?'],
            ['number' => 53, 'subject' => '¿Concuerda su forma de pensar con la de Dios?'],
            ['number' => 54, 'subject' => 'Edifique su fe en el Hacedor del hombre'],
            ['number' => 55, 'subject' => '¿Qué clase de nombre se está haciendo con Dios?'],
            ['number' => 56, 'subject' => 'Hacia el nuevo mundo bajo el acaudillamiento de Cristo'],
            ['number' => 57, 'subject' => 'Aguantemos la persecución'],
            ['number' => 58, 'subject' => '¿Cómo debemos servir a Dios?'],
            ['number' => 59, 'subject' => 'Se siega lo que se siembra'],
            ['number' => 60, 'subject' => '¿Qué propósito tiene su vida?'],
            ['number' => 61, 'subject' => '¿En las promesas de quién confía usted?'],
            ['number' => 62, 'subject' => 'El único remedio para la humanidad enferma'],
            ['number' => 63, 'subject' => '¿Tiene usted espíritu evangelizador?'],
            ['number' => 64, 'subject' => '¿Amadores del placer, o amadores de Dios?'],
            ['number' => 65, 'subject' => 'Cómo hallar honra y gozo en el ministerio de Dios'],
            ['number' => 66, 'subject' => 'Trabaje como esclavo para el amo de la siega'],
            ['number' => 67, 'subject' => 'Dedique tiempo a meditar en asuntos espirituales'],
            ['number' => 68, 'subject' => '¿Guarda usted rencor o perdona?'],
            ['number' => 69, 'subject' => 'Renovemos el espíritu de abnegación'],
            ['number' => 70, 'subject' => 'Cifre su confianza en Jehová'],
            ['number' => 71, 'subject' => 'Cómo mantenerse despierto espiritualmente'],
            ['number' => 72, 'subject' => 'El amor identifica a la congregación cristiana verdadera'],
            ['number' => 73, 'subject' => 'Adquiera un corazón de sabiduría'],
            ['number' => 74, 'subject' => 'Los ojos de Jehová están sobre nosotros'],
            ['number' => 75, 'subject' => '¿Reconoce usted la soberanía de Jehová en su vida personal?'],
            ['number' => 76, 'subject' => '¿Pueden los principios bíblicos ayudarnos a afrontar los problemas de nuestro tiempo?'],
            ['number' => 77, 'subject' => 'Siga la senda de la hospitalidad'],
            ['number' => 78, 'subject' => 'Sirva a Jehová con corazón gozoso'],
            ['number' => 79, 'subject' => 'La amistad con Dios o la amistad con el mundo: ¿cuál escogerá usted?'],
            ['number' => 80, 'subject' => '¿Cifra usted su esperanza en la ciencia, o en la Biblia?'],
            ['number' => 81, 'subject' => '¿Quiénes llenan los requisitos para ser ministros de Dios?'],
            ['number' => 82, 'subject' => 'Jehová y Cristo: ¿son ellos parte de una trinidad?'],
            ['number' => 83, 'subject' => 'El tiempo de juicio para la religión'],
            ['number' => 84, 'subject' => '¿Escapará usted de lo que le espera a este mundo?'],
            ['number' => 85, 'subject' => 'Buenas nuevas en un mundo violento'],
            ['number' => 86, 'subject' => 'Las oraciones que Dios escucha'],
            ['number' => 87, 'subject' => '¿Qué relación tiene usted con Dios?'],
            ['number' => 88, 'subject' => '¿Por qué regir su vida por las normas bíblicas?'],
            ['number' => 89, 'subject' => '¡Venga, el que tenga sed de la verdad!'],
            ['number' => 90, 'subject' => '¡Esfuércese por lo que realmente es vida!'],
            ['number' => 91, 'subject' => 'La presencia y la gobernación del Mesías'],
            ['number' => 92, 'subject' => 'El papel de la religión en los asuntos del mundo'],
            ['number' => 93, 'subject' => '¿Es Dios el causante de los desastres naturales?'],
            ['number' => 94, 'subject' => 'La religión verdadera satisface las necesidades de la sociedad humana'],
            ['number' => 95, 'subject' => 'La Biblia ante las prácticas espiritistas'],
            ['number' => 96, 'subject' => 'El fin de la religión falsa está cerca'],
            ['number' => 97, 'subject' => 'Permanezcamos sin culpa en medio de una generación torcida'],
            ['number' => 98, 'subject' => 'No dejemos que este mundo nos contamine'],
            ['number' => 99, 'subject' => 'Por qué se puede confiar en la Biblia'],
            ['number' => 100, 'subject' => 'La amistad verdadera con Dios y con el prójimo'],
            ['number' => 101, 'subject' => 'Jehová, el Magnífico Creador'],
            ['number' => 102, 'subject' => 'Prestemos atención a la Palabra profética'],
            ['number' => 103, 'subject' => 'Usted puede experimentar gozo al servir a Dios'],
            ['number' => 104, 'subject' => 'Padres, ¿están edificando con materiales incombustibles?'],
            ['number' => 105, 'subject' => 'Cómo obtener consuelo en toda tribulación'],
            ['number' => 106, 'subject' => 'Dios dará su merecido a los que arruinan la Tierra'],
            ['number' => 107, 'subject' => 'Mantengamos una buena conciencia en un mundo pecador'],
            ['number' => 108, 'subject' => 'Superemos el temor al futuro'],
            ['number' => 109, 'subject' => 'El Reino de Dios está cerca'],
            ['number' => 110, 'subject' => 'La familia feliz es la que pone a Dios en primer lugar'],
            ['number' => 111, 'subject' => '¿Qué logra la curación de las naciones?'],
            ['number' => 112, 'subject' => 'Cómo mostrar amor en un mundo desaforado'],
            ['number' => 113, 'subject' => '¿Cómo pueden los jóvenes hacer frente a la crisis actual?'],
            ['number' => 114, 'subject' => 'Aprecie las maravillas de la creación de Dios'],
            ['number' => 115, 'subject' => 'Cómo protegernos de las trampas de Satanás'],
            ['number' => 116, 'subject' => 'Sea sabio al elegir sus compañías'],
            ['number' => 117, 'subject' => 'Cómo vencer el mal con el bien'],
            ['number' => 118, 'subject' => 'Veamos a los jóvenes como los ve Jehová'],
            ['number' => 119, 'subject' => 'Por qué es provechoso que los cristianos se mantengan separados del mundo'],
            ['number' => 120, 'subject' => 'Razones para someterse hoy al gobierno de Dios'],
            ['number' => 121, 'subject' => 'Una hermandad mundial rescatada de la calamidad'],
            ['number' => 122, 'subject' => '¿De qué fuente vendrá la paz mundial?'],
            ['number' => 123, 'subject' => 'Por qué deben ser diferentes los cristianos'],
            ['number' => 124, 'subject' => 'Razones para confiar en el origen divino de la Biblia'],
            ['number' => 125, 'subject' => 'Por qué necesita la humanidad un rescate'],
            ['number' => 126, 'subject' => '¿Quién puede ser salvo?'],
            ['number' => 127, 'subject' => '¿Qué nos sucede cuando morimos?'],
            ['number' => 128, 'subject' => '¿Es el infierno realmente un lugar de tormento?'],
            ['number' => 129, 'subject' => '¿Es la Trinidad una enseñanza bíblica?'],
            ['number' => 130, 'subject' => 'La Tierra existirá para siempre'],
            ['number' => 131, 'subject' => '¿De verdad existe el Diablo?'],
            ['number' => 132, 'subject' => 'La resurrección: una victoria sobre la muerte'],
            ['number' => 133, 'subject' => '¿Importa lo que creemos sobre el origen de los seres humanos?'],
            ['number' => 134, 'subject' => '¿Deben guardar los cristianos un día de descanso?'],
            ['number' => 135, 'subject' => 'La santidad de la vida y la sangre'],
            ['number' => 136, 'subject' => '¿Aprueba Dios las imágenes en la adoración?'],
            ['number' => 137, 'subject' => '¿De verdad tuvieron lugar los milagros de la Biblia?'],
            ['number' => 138, 'subject' => 'Vivamos con buen juicio en un mundo perverso'],
            ['number' => 139, 'subject' => 'Sabiduría piadosa en un mundo de orientación científica'],
            ['number' => 140, 'subject' => 'Jesucristo: el nuevo gobernante de la Tierra'],
            ['number' => 141, 'subject' => '¿Cuándo dejará de gemir la creación humana?'],
            ['number' => 142, 'subject' => 'Por qué refugiarse en Jehová'],
            ['number' => 143, 'subject' => 'Confiemos en el Dios de todo consuelo'],
            ['number' => 144, 'subject' => 'Una congregación leal bajo la dirección de Cristo'],
            ['number' => 145, 'subject' => '¿Quién es como Jehová nuestro Dios?'],
            ['number' => 146, 'subject' => 'Utilice la educación para alabar a Jehová'],
            ['number' => 147, 'subject' => 'Confíe en el poder salvador de Jehová'],
            ['number' => 148, 'subject' => '¿Ve usted la vida como la ve Dios?'],
            ['number' => 149, 'subject' => '¿Anda usted con Dios?'],
            ['number' => 150, 'subject' => '¿Hasta qué grado es Dios real para usted?'],
            ['number' => 151, 'subject' => 'Jehová es “una altura segura” para su pueblo'],
            ['number' => 152, 'subject' => '¿Cuándo y por qué vendrá el verdadero Armagedón?'],
            ['number' => 153, 'subject' => 'Tengamos muy presente el día “inspirador de temor”'],
            ['number' => 154, 'subject' => 'El gobierno del hombre, pesado en la balanza'],
            ['number' => 155, 'subject' => '¿Ha llegado la hora del juicio de Babilonia?'],
            ['number' => 156, 'subject' => '¿Es el Día del Juicio un tiempo de temor, o de esperanza?'],
            ['number' => 157, 'subject' => 'Cómo adornan los cristianos la enseñanza divina'],
            ['number' => 158, 'subject' => 'Seamos valerosos y confiemos en Jehová'],
            ['number' => 159, 'subject' => 'Cómo encontrar seguridad en un mundo peligroso'],
            ['number' => 160, 'subject' => 'Protejamos nuestra identidad cristiana'],
            ['number' => 161, 'subject' => '¿Por qué sufrió y murió Jesús?'],
            ['number' => 162, 'subject' => 'Liberados de un mundo de oscuridad'],
            ['number' => 163, 'subject' => '¿Por qué temer al Dios verdadero?'],
            ['number' => 164, 'subject' => '¿Sigue Dios ejerciendo la soberanía sobre la Tierra?'],
            ['number' => 165, 'subject' => '¿A qué valores concedemos más importancia?'],
            ['number' => 166, 'subject' => 'Afrontemos el futuro con fe y valor'],
            ['number' => 167, 'subject' => 'Actuemos con sabiduría en este mundo insensato'],
            ['number' => 168, 'subject' => 'Cómo sentirse seguro en este mundo turbulento'],
            ['number' => 169, 'subject' => '¿Por qué debemos guiarnos por la Biblia?'],
            ['number' => 170, 'subject' => '¿Quién es el único que puede gobernar bien a la humanidad?'],
            ['number' => 171, 'subject' => 'Usted puede disfrutar de la vida en paz ahora y para siempre'],
            ['number' => 172, 'subject' => '¿Qué posición tenemos ante Dios?'],
            ['number' => 173, 'subject' => '¿Le importa a Dios qué religión tengamos?'],
            ['number' => 174, 'subject' => '¿Quién será digno de entrar en el nuevo mundo de Dios?'],
            ['number' => 175, 'subject' => '¿Qué pruebas demuestran la autenticidad de la Biblia?'],
            ['number' => 176, 'subject' => '¿Cuándo tendremos verdadera paz y seguridad?'],
            ['number' => 177, 'subject' => '¿A quién podemos acudir en tiempos de angustia?'],
            ['number' => 178, 'subject' => 'Andemos en el camino de la integridad'],
            ['number' => 179, 'subject' => 'Rechace las fantasías mundanales; busque las realidades del Reino'],
            ['number' => 180, 'subject' => '¿Por qué debe ser real para nosotros la esperanza de la resurrección?'],
            ['number' => 181, 'subject' => '¿Faltará menos de lo que usted cree?'],
            ['number' => 182, 'subject' => '¿Qué está haciendo por nosotros el Reino de Dios?'],
            ['number' => 183, 'subject' => 'Alejemos la mirada de lo que es inútil'],
        ];

        $en_talks = [
            ['number' => 1, 'subject' => 'How Well Do You Know God?'],
            ['number' => 2, 'subject' => 'Will You Be a Survivor of the Last Days?'],
            ['number' => 3, 'subject' => 'Serving With Jehovah’s Unified Organization'],
            ['number' => 4, 'subject' => 'Evidence of God in the World Around Us'],
            ['number' => 5, 'subject' => 'Family Life That Warms the Heart'],
            ['number' => 6, 'subject' => 'The Flood of Noah’s Day Has Meaning for Us'],
            ['number' => 7, 'subject' => 'Mercy, a Dominant Quality of True Christians'],
            ['number' => 8, 'subject' => 'Living, Not for Self, But to Do God’s Will'],
            ['number' => 9, 'subject' => 'Never Become Dull in Your Hearing'],
            ['number' => 10, 'subject' => 'Conducting Ourselves Honestly at All Times'],
            ['number' => 11, 'subject' => '“No Part of the World”—In Imitation of Christ'],
            ['number' => 12, 'subject' => 'Respect for Authority Is a Safeguard for You'],
            ['number' => 13, 'subject' => 'A Godly View of Sex and Marriage'],
            ['number' => 14, 'subject' => 'A Clean People Honors Jehovah'],
            ['number' => 15, 'subject' => 'As Christians, We Care About Other People'],
            ['number' => 16, 'subject' => 'Keep Growing in Your Relationship With God'],
            ['number' => 17, 'subject' => 'Glorifying God With All We Have'],
            ['number' => 18, 'subject' => 'Are You Really Making Jehovah Your Stronghold?'],
            ['number' => 19, 'subject' => 'Your Future—How Can It Be Known?'],
            ['number' => 20, 'subject' => 'Is It Time for God to Rule the World?'],
            ['number' => 21, 'subject' => 'How Do You Fit Into the Kingdom Arrangement?'],
            ['number' => 22, 'subject' => 'Are You Content With Jehovah’s Provisions?'],
            ['number' => 23, 'subject' => 'Life Does Have a Purpose'],
            ['number' => 24, 'subject' => 'What God’s Rulership Can Do for Us'],
            ['number' => 25, 'subject' => 'Resisting the Spirit of the World'],
            ['number' => 26, 'subject' => 'Does God Count You Personally Important?'],
            ['number' => 27, 'subject' => 'Getting Marriage Off to a Good Start'],
            ['number' => 28, 'subject' => 'Show Respect and Love in Your Marriage'],
            ['number' => 29, 'subject' => 'Responsibilities and Rewards of Parenthood'],
            ['number' => 30, 'subject' => 'Communication—Within the Family and With God'],
            ['number' => 31, 'subject' => 'Happy Though Hungry—How Can It Be?'],
            ['number' => 32, 'subject' => 'Coping With Life’s Anxieties'],
            ['number' => 33, 'subject' => 'What Is Behind the Spirit of Rebellion?'],
            ['number' => 34, 'subject' => 'Are You “Marked” for Survival?'],
            ['number' => 35, 'subject' => 'Can You Live Forever? Will You?'],
            ['number' => 36, 'subject' => 'Is This Life All There Is?'],
            ['number' => 37, 'subject' => 'Decide Now for Divine Rulership'],
            ['number' => 38, 'subject' => 'Act Wisely as the End Draws Near'],
            ['number' => 39, 'subject' => 'Be Confident of Divine Victory!'],
            ['number' => 40, 'subject' => 'What the Near Future Holds!'],
            ['number' => 41, 'subject' => '“Stand Still and See the Salvation of Jehovah”'],
            ['number' => 42, 'subject' => 'How the Kingdom of God Affects You'],
            ['number' => 43, 'subject' => 'Are You Doing What God Requires of You?'],
            ['number' => 44, 'subject' => 'Keep Seeking God’s Kingdom'],
            ['number' => 45, 'subject' => 'Follow the Way to Life'],
            ['number' => 46, 'subject' => 'Maintain Your Confidence Firm to the End'],
            ['number' => 47, 'subject' => '“Have Faith in the Good News”'],
            ['number' => 48, 'subject' => 'Meeting the Test of Christian Loyalty'],
            ['number' => 49, 'subject' => 'A Cleansed Earth—Will You Live to See It?'],
            ['number' => 50, 'subject' => 'Decisions You Face—How Will You Make Them?'],
            ['number' => 51, 'subject' => 'Is the Truth Transforming Your Life?'],
            ['number' => 52, 'subject' => 'Who Is Your God?'],
            ['number' => 53, 'subject' => 'Does Your Thinking Agree With God’s?'],
            ['number' => 54, 'subject' => 'Build Your Faith in Man’s Maker'],
            ['number' => 55, 'subject' => 'What Kind of Name Are You Making With God?'],
            ['number' => 56, 'subject' => 'Into the New World Under Christ’s Leadership'],
            ['number' => 57, 'subject' => 'Bearing Up Under Persecution'],
            ['number' => 58, 'subject' => 'How Should You Serve God?'],
            ['number' => 59, 'subject' => 'You Will Reap What You Sow'],
            ['number' => 60, 'subject' => 'How Purposeful Is Your Life?'],
            ['number' => 61, 'subject' => 'On Whose Promises Do You Rely?'],
            ['number' => 62, 'subject' => 'The Only Cure for Sick Mankind'],
            ['number' => 63, 'subject' => 'Do You Have the Evangelizing Spirit?'],
            ['number' => 64, 'subject' => 'Lovers of Pleasure or Lovers of God?'],
            ['number' => 65, 'subject' => 'Finding Honor and Joy in God’s Ministry'],
            ['number' => 66, 'subject' => 'Slave for the Master of the Harvest'],
            ['number' => 67, 'subject' => 'Taking Time to Meditate on Spiritual Things'],
            ['number' => 68, 'subject' => 'Do You Harbor Resentment, or Do You Forgive?'],
            ['number' => 69, 'subject' => 'Renewing the Spirit of Self-Sacrifice'],
            ['number' => 70, 'subject' => 'Make Jehovah Your Confidence'],
            ['number' => 71, 'subject' => 'How to Keep Spiritually Awake'],
            ['number' => 72, 'subject' => 'Love Identifies the True Christian Congregation'],
            ['number' => 73, 'subject' => 'Acquiring a Heart of Wisdom'],
            ['number' => 74, 'subject' => 'Jehovah’s Eyes Are Upon Us'],
            ['number' => 75, 'subject' => 'Do You Recognize Jehovah’s Sovereignty in Your Personal Life?'],
            ['number' => 76, 'subject' => 'Bible Principles—Can They Help Us to Cope With Today’s Problems?'],
            ['number' => 77, 'subject' => 'Follow the Course of Hospitality'],
            ['number' => 78, 'subject' => 'Serve Jehovah With a Joyful Heart'],
            ['number' => 79, 'subject' => 'Friendship With God, Friendship With the World —Which Will You Choose?'],
            ['number' => 80, 'subject' => 'Does Your Hope Rest on Science or the Bible?'],
            ['number' => 81, 'subject' => 'Who Are Qualified as Ministers of God?'],
            ['number' => 82, 'subject' => 'Jehovah and Christ—Are They Part of a Trinity?'],
            ['number' => 83, 'subject' => 'Religion’s Time of Judgment'],
            ['number' => 84, 'subject' => 'Will You Escape This World’s Destiny?'],
            ['number' => 85, 'subject' => 'Good News in a Violent World'],
            ['number' => 86, 'subject' => 'Prayers That Are Heard by God'],
            ['number' => 87, 'subject' => 'What Is Your Relationship With God?'],
            ['number' => 88, 'subject' => 'Why Live by Bible Standards?'],
            ['number' => 89, 'subject' => 'Come, You Who Thirst for the Truth!'],
            ['number' => 90, 'subject' => 'Reach Out for the Real Life!'],
            ['number' => 91, 'subject' => 'The Messiah’s Presence and His Rule'],
            ['number' => 92, 'subject' => 'Religion’s Role in World Affairs'],
            ['number' => 93, 'subject' => '“Acts of God”—How Do You View Them?'],
            ['number' => 94, 'subject' => 'True Religion Meets the Needs of Human Society'],
            ['number' => 95, 'subject' => 'The Bible’s View of Spiritistic Practices'],
            ['number' => 96, 'subject' => 'False Religion’s End Is Near'],
            ['number' => 97, 'subject' => 'Remaining Blameless Amid a Crooked Generation'],
            ['number' => 98, 'subject' => 'Keep Clean From Worldly Defilements'],
            ['number' => 99, 'subject' => 'Why You Can Trust the Bible'],
            ['number' => 100, 'subject' => 'True Friendship With God and Neighbor'],
            ['number' => 101, 'subject' => 'Jehovah—The Grand Creator'],
            ['number' => 102, 'subject' => 'Paying Attention to the Prophetic Word'],
            ['number' => 103, 'subject' => 'You Can Find Joy in Serving God'],
            ['number' => 104, 'subject' => 'Parents—Are You Building With Fire-Resistant Materials?'],
            ['number' => 105, 'subject' => 'Gaining Comfort in All Our Tribulations'],
            ['number' => 106, 'subject' => 'Ruining the Earth Brings Divine Retribution'],
            ['number' => 107, 'subject' => 'Hold a Good Conscience in a Sinful World'],
            ['number' => 108, 'subject' => 'Overcoming Fear of the Future'],
            ['number' => 109, 'subject' => 'The Kingdom of God Is Near'],
            ['number' => 110, 'subject' => 'God Comes First in Successful Family Life'],
            ['number' => 111, 'subject' => 'What Does the Healing of the Nations Accomplish?'],
            ['number' => 112, 'subject' => 'How to Express Love in a Lawless World'],
            ['number' => 113, 'subject' => 'How Can Youths Cope With Today’s Crisis?'],
            ['number' => 114, 'subject' => 'Appreciating Marvels of God’s Creation'],
            ['number' => 115, 'subject' => 'How to Protect Ourselves From Satan’s Snares'],
            ['number' => 116, 'subject' => 'Choose Your Associates Wisely!'],
            ['number' => 117, 'subject' => 'How to Conquer Evil With Good'],
            ['number' => 118, 'subject' => 'Looking at Youths From Jehovah’s Standpoint'],
            ['number' => 119, 'subject' => 'Christian Separateness From the World —Why Beneficial'],
            ['number' => 120, 'subject' => 'Why Submit to God’s Rulership Now'],
            ['number' => 121, 'subject' => 'A Worldwide Brotherhood Saved From Calamity'],
            ['number' => 122, 'subject' => 'Global Peace—From What Source?'],
            ['number' => 123, 'subject' => 'Why Christians Must Be Different'],
            ['number' => 124, 'subject' => 'Basis for Confidence in the Bible’s Divine Authorship'],
            ['number' => 125, 'subject' => 'Why Mankind Needs a Ransom'],
            ['number' => 126, 'subject' => 'Who Can Be Saved?'],
            ['number' => 127, 'subject' => 'What Happens When We Die?'],
            ['number' => 128, 'subject' => 'Is Hell Really a Place of Fiery Torment?'],
            ['number' => 129, 'subject' => 'Is the Trinity a Scriptural Teaching?'],
            ['number' => 130, 'subject' => 'The Earth Will Remain Forever'],
            ['number' => 131, 'subject' => 'Is There Really a Devil?'],
            ['number' => 132, 'subject' => 'The Resurrection—Victory Over Death!'],
            ['number' => 133, 'subject' => 'The Origin of Humans—Does It Matter What You Believe?'],
            ['number' => 134, 'subject' => 'Should Christians Keep the Sabbath?'],
            ['number' => 135, 'subject' => 'The Sacredness of Life and Blood'],
            ['number' => 136, 'subject' => 'Does God Approve of the Use of Images in Worship?'],
            ['number' => 137, 'subject' => 'Did the Miracles of the Bible Really Happen?'],
            ['number' => 138, 'subject' => 'Live With Soundness of Mind in a Depraved World'],
            ['number' => 139, 'subject' => 'Godly Wisdom in a Scientific World'],
            ['number' => 140, 'subject' => 'Jesus Christ—Earth’s New Ruler'],
            ['number' => 141, 'subject' => 'Human Creation’s Groaning—When Will It End?'],
            ['number' => 142, 'subject' => 'Why Take Refuge in Jehovah'],
            ['number' => 143, 'subject' => 'Trust in the God of All Comfort'],
            ['number' => 144, 'subject' => 'A Loyal Congregation Under Christ’s Leadership'],
            ['number' => 145, 'subject' => 'Who Is Like Jehovah Our God?'],
            ['number' => 146, 'subject' => 'Use Education to Praise Jehovah'],
            ['number' => 147, 'subject' => 'Trust in Jehovah’s Saving Power'],
            ['number' => 148, 'subject' => 'Do You Share God’s View of Life?'],
            ['number' => 149, 'subject' => 'Are You Walking With God?'],
            ['number' => 150, 'subject' => 'How Real Is God to You?'],
            ['number' => 151, 'subject' => 'Jehovah Is “a Secure Height” for His People'],
            ['number' => 152, 'subject' => 'The Real Armageddon—Why? When?'],
            ['number' => 153, 'subject' => 'Keep Close in Mind the “Fear-Inspiring Day”!'],
            ['number' => 154, 'subject' => 'Human Rule—Weighed in the Balance'],
            ['number' => 155, 'subject' => 'Has Babylon’s Judgment Hour Arrived?'],
            ['number' => 156, 'subject' => 'Judgment Day—ATime of Fear or Hope?'],
            ['number' => 157, 'subject' => 'How True Christians Adorn Divine Teaching'],
            ['number' => 158, 'subject' => 'Be Courageous, and Trust in Jehovah'],
            ['number' => 159, 'subject' => 'Finding Security in a Dangerous World'],
            ['number' => 160, 'subject' => 'Safeguard Your Christian Identity!'],
            ['number' => 161, 'subject' => 'Why Did Jesus Suffer and Die?'],
            ['number' => 162, 'subject' => 'Deliverance From a World of Darkness'],
            ['number' => 163, 'subject' => 'Why Fear the True God?'],
            ['number' => 164, 'subject' => 'Is God Still in Control?'],
            ['number' => 165, 'subject' => 'Whose Values Do You Cherish?'],
            ['number' => 166, 'subject' => 'Facing the Future With Faith and Courage'],
            ['number' => 167, 'subject' => 'Act Wisely in a Senseless World'],
            ['number' => 168, 'subject' => 'You Can Feel Safe in This Troubled World!'],
            ['number' => 169, 'subject' => 'Why Be Guided by the Bible?'],
            ['number' => 170, 'subject' => 'Who Is Qualified to Rule Mankind?'],
            ['number' => 171, 'subject' => 'You Can Enjoy Life in Peace Now—And Forever!'],
            ['number' => 172, 'subject' => 'What Is Your Standing With God?'],
            ['number' => 173, 'subject' => 'Is There a True Religion From God’s Standpoint?'],
            ['number' => 174, 'subject' => 'God’s New World—Who Will Qualify to Enter?'],
            ['number' => 175, 'subject' => 'What Marks the Bible as Authentic?'],
            ['number' => 176, 'subject' => 'Real Peace and Security—When?'],
            ['number' => 177, 'subject' => 'Where Can You Get Help in Times of Distress?'],
            ['number' => 178, 'subject' => 'Walk in the Way of Integrity'],
            ['number' => 179, 'subject' => 'Reject Worldly Fantasies, Pursue Kingdom Realities'],
            ['number' => 180, 'subject' => 'The Resurrection—Why That Hope Should Be Real to You'],
            ['number' => 181, 'subject' => 'Is It Later Than You Think?'],
            ['number' => 182, 'subject' => 'What God’s Kingdom Is Doing for Us Now'],
            ['number' => 183, 'subject' => 'Turn Your Eyes Away From Worthless Things!'],
        ];

        $admin = User::first();

        $ht = Locale::where('code', 'ht')->first();
        foreach ($ht_talks as $ht_talk) {
            $talk = $this->findOrSaveTalk($ht_talk['number'], $admin);
            $this->saveTalkSubject($ht_talk['subject'], $talk, $ht, $admin);
        }

        $es = Locale::where('code', 'es')->first();
        foreach ($es_talks as $es_talk) {
            $talk = $this->findOrSaveTalk($es_talk['number'], $admin);
            $this->saveTalkSubject($es_talk['subject'], $talk, $es, $admin);
        }

        $en = Locale::where('code', 'en')->first();
        foreach ($en_talks as $en_talk) {
            $talk = $this->findOrSaveTalk($en_talk['number'], $admin);
            $this->saveTalkSubject($en_talk['subject'], $talk, $en, $admin);
        }
    }

    protected function findOrSaveTalk($number, User $user)
    {
        $talk = Talk::where('number', $number)->first();

        if (!isset($talk)) {
            $talk = new Talk();
            $talk->number = $number;
            $talk->createdBy()->associate($user);
            $talk->updatedBy()->associate($user);
            $talk->save();
        }

        return $talk;
    }

    protected function saveTalkSubject($subject, Talk $talk, Locale $locale, User $user)
    {
        $talk_subject = new TalkSubject();
        $talk_subject->subject = $subject;
        $talk_subject->talk()->associate($talk);
        $talk_subject->locale()->associate($locale);
        $talk_subject->createdBy()->associate($user);
        $talk_subject->updatedBy()->associate($user);
        $talk_subject->save();

        return $talk_subject;
    }
}
